### PR TITLE
Expose different rpcapi configurations on geth nodes

### PR DESCRIPTION
**Pull request by zomglings**
Resolves https://github.com/the-chaingang/ethereal/issues/25

Run `tests/rpc-api` to verify.

### CODE REVIEW

**Comment by zomglings** [comment]
@olawiberg : Please have a look.

**Comment by olawiberg** [comment]
@nkashy1 I found a few issues with the test setup when running this. 

1. If the test fails, the docker containers continue running, we need a way to automatically bring down the containers when the tests fail.
1. When tests succeed and Docker compose brings down the containers the network is not removed. This causes the following test-runs to fail as it complains that the network already exists. Doing `docker network rm <network-id>` and then running the test solves the problem. Can this be automated?

**Comment by zomglings** [comment]
Thanks @olawiberg.

1. It is important to pass the `--exit-code-from test` argument to `docker-compose up` when you run the test.

2. If you run `docker-compose down -v` after the test has run, the volumes and networks created as part of the test run will be removed.

**Comment by zomglings** [comment]
After discussion with @olawiberg, we realized that he had the expectation that this testing procedure would be comprehensive in the sense that it would handle the setup and teardown phase of testing as well.

The intention with this PR is to set up a base testing implementation that we can improve to accommodate setup and teardown through proposals like https://github.com/the-chaingang/ethereal/issues/24

Does that sound right to you @olawiberg ?

**Comment by olawiberg** [comment]
@nkashy1 yes, that sounds right. I understand now that this is just creating the base mechanics for testing and implementing Mocha (Issue #24) would help with the full orchestration of the tests.

**Comment by zomglings** [comment]
@olawiberg : Exactly, although the exact choice of test runner (mocha or something else) depends on your and @akshr's reviews of #24 .

One thing that occurred as part of this review process is that we realized that reusing the same external IP on the network could cause conflicts between tests (if we want two tests to run concurrently). I propose that we merge this PR (if it meets your approval) and raise that as a separate issue.

**Review by olawiberg — APPROVED** [review]
Looks good. I tested it and it works fine.

**Pull request merged**
