### PR TITLE
Testing framework + initial tests

### PR DESCRIPTION
**Pull request by zomglings**
This pertains to https://github.com/the-chaingang/ethereal/issues/20 and constitutes a rough solution - I added a test which brings up an ethereal network with two full nodes and checks that both nodes have a single peer.

I would like some feedback and discussion about the usability of this solution before we merge this PR.

### CODE REVIEW

**Comment by zomglings** [comment]
As of latest commit, the test now also builds the test image - simply `cd` into `tests/connectivity` and run ```ETHEREAL_TAG=v0.4-release-1.7 docker-compose up --build --exit-code-from test```

Once the test is done, run ```docker-compose down -v```

One TODO item that came up from this is that we need a more principled docker networking story in the `docker-compose` files - the current setup works but there is probably a better way to specify and then parametrize the network with docker primitives. This is yet another type of thing that we can quickly improve upon with a testing framework like this in place.

**Comment by zomglings** [comment]
@olawiberg , @shad0wfax : I am thinking of wrapping up our test runs (which will use `docker-compose` under the hood) in `mocha`. Will make it easier to manage the test runs programmatically (for example, using the [child process standard library](https://nodejs.org/api/child_process.html)).

I feel as if `bash` is already adding friction for us, and will not even run on a large number of user environments (how many Windows users have access to `bash`?).

What do you guys think?

Edit: To be clear, I think we should actually merge this PR and track any such work with a separate issue.

Edit 2: Tracking issue here - https://github.com/the-chaingang/ethereal/issues/24

**Review by olawiberg — APPROVED** [review]
Beautiful! I tried a few different options for pass/fail and it works great.

**Comment by zomglings** [comment]
@olawiberg : Thanks for having a look at this, and it made my day that you seemed to enjoy the experience. :smiley:

**Pull request merged**
